cosmo_tester/resources/blueprints/openstack-start-vm/blueprint.yaml, cosmo_tester/test_suites/test_simple_manager_blueprint/nodecellar_singlehost_test.py
Opened port 8086 since the test assertions require it. 
Using private ip as input for single host nodecellar.
=> CFY-2613 added external network property to the simple manager inputs.

suites/suites/suites.yaml
CFY-4061-new-manager-blueprint-as-default
needs to be merged alongside same branch in:
Cloudify dev
Cloudify Packager
Cloudify Manager
=> CFY-4061-new-manager-blueprint-as-default [ci skip]

suites/suites/suites.yaml
added
it's used in this: https://github.com/cloudify-cosmo/cloudify-aws-plugin/blob/CFY-4154-Add-Cloud-Init-Agent-Installation/system_tests/manager/aws_ec2_user_data_agent_install_test.py#L60
=> need to have a centos7 ami avialable in test context

suites/suites/suites.yaml
Also concerning why the error that says this variable did't exist isn't in the test error output
=> CFY-4871 added the aws_ec2_frankfurt_rhel_65_image_id

circle.yml, setup.py, suites/Vagrantfile.template, suites/helpers/__init__.py, suites/helpers/password_store.py, suites/helpers/suites_builder.py, suites/helpers/variables_builder.py, suites/requirements.txt, suites/suites_runner.py, suites/suites_runner.sh, suites/tests/test_scheduler.py, test-requirements.txt
* Some of the changes in this PR are just refactoring.
* There is no longer a concept of skipped suites. It used to exist before we added the `clean_all` to handlers. Now, if a suite times out, other suites that need that environment can still use it because they will cleanup before. This is why `remove_env`
was also removed in this PR.
* Refactored the lock env and release env concepts so that different implementations can be provided. Previous implementation is now named `InMemoryEnvironments` and it is currently only used in unit tests. New `FileEnvironments` implementation makes use of a shared (lock protected) file and is suitable for use on a single jenkins slave by multiple processes. The current path chosen to store this file is the root of the virtualenv that is shared by system …
=> CFY-4417 Allow concurrent system tests execution

cosmo_tester/test_suites/backwards/test_nodecellar_backwards_compatibility/nodecellar_backwards_compatibility_test_base.py, cosmo_tester/test_suites/test_blueprints/elasticsearch_test.py, cosmo_tester/test_suites/test_blueprints/neutron_galore_test.py, cosmo_tester/test_suites/test_blueprints/nodecellar_test.py, cosmo_tester/test_suites/test_blueprints/test_existing_vm.py, cosmo_tester/test_suites/test_broker_security/broker_security_test_base.py, cosmo_tester/test_suites/test_external_components/base_external_components.py, cosmo_tester/test_suites/test_security/security_test_base.py, cosmo_tester/test_suites/test_simple_manager_blueprint/abstract_single_host_test.py, cosmo_tester/test_suites/test_snapshots/snapshots_migration_from_321_to_33_test.py
Operations that can partially fail, and that need some cleanup
(eg. the install/uninstall workflows) need to have their cleanup
scheduled (using .addCleanup) BEFORE running them.
In case the operation (eg. install) fails partway, and throws an
exception, the .addCleanup call might be skipped because of the
exception, and the uninstall won't run, leaving the system with
a partially-executed workflow that was never cleaned up after.
This change makes sure that all .addCleanup calls are always scheduled
before the risky operation they're cleaning up after.
This also uses the new openstack plugin API for removing keypairs.
=> CFY-4607 cleanup: each test removes keypairs it creates

cosmo_tester/framework/cfy_helper.py, cosmo_tester/test_suites/test_manager_upgrade/__init__.py, cosmo_tester/test_suites/test_manager_upgrade/manager_upgrade_test.py, suites/suites/suites.yaml
Add a test for the manager upgrade procedure:
- bootstrap a 3.4m5 manager (currently openstack only)
- deploy a hello world app
- upgrade the manager to the master branch (of the blueprint)
- check that everything still works
- rollback the manager to the original state.
=> CFY-5317 Manager upgrade test

cosmo_tester/framework/util.py
This way, we both print out the stderr/stdout, and can access the
.stderr/.stdout attributes on sh's return values and exceptions.
Without passing it back to process._stdout/process._stderr, we only
print it out, but returned values are empty strings.
This way, we don't need to mock stdout when making assertions about
cfy output - simply check the retval's/exception's .stdout/.stderr
=> sh_bake: also pass stdout/stderr back to sh

cosmo_tester/framework/util.py, cosmo_tester/resources/plugins/mock-auth-provider-with-no-userstore/mock_auth_provider_with_no_userstore/auth_without_userstore.py
The old one would remove trailing padding `=`'s, which caused problems for flask-security
=> CFY-5948 Replace base64 encode function

cosmo_tester/test_suites/agent/test_agent_installer.py
* The file server is now always internally accessed via the REST's port (with a /resources suffix), and is then redirected to  its internal port
* All the folder names now reside in cloudify-plugins-common.constants (seeing as how they are indeed constants)
* All the workers (agent + mgmt) now need to have much fewer params regarding the file server
=> CFY-6492 Make the file server always secured

cosmo_tester/test_suites/image_based_tests/auto_heal_test.py
Only to be merged once riemann changes are done on manager blueprints.
=> CFY-6747-Re-enable auto heal checks

cosmo_tester/test_suites/image_based_tests/deployment_update_test.py
This folder has funky permissions, and it messes up the upload manager
=> CFY-6790 Remove .git folder in deployment update test

cosmo_tester/framework/cluster.py
Eg. cli version "4.0.1" is translated to
"cloudify-manager-premium-4.0.1"
=> Get image name: handle CLI versions without a dash

cosmo_tester/test_suites/image_based_tests/agent_installation_test.py
This is instead of inferring whether sudo is needed from the install
method.
The only 3 cases that use the `init_script` method are:
1. Regular userdata - in which case sudo is not needed
2. Agents upgrade - in which case the install method would be
irrelevant in any case, and passing an argument would be necessary
3. System tests/other provided scenarios - in which case it is
somewhat more flexible (and up to the user) to require providing
the argument
=> CFY-7124 Make the `install_with_sudo` param mandatory

cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py
After removing each node, we don't necessarily know which node is
going to be the master, so we need to check all non-removed nodes,
not just the expected master.
=> test_remove_manager_from_cluster: wait correctly after removing nodes

cosmo_tester/framework/cluster.py, cosmo_tester/framework/util.py, cosmo_tester/resources/attributes.yaml, cosmo_tester/test_suites/bootstrap_based_tests/cli_test.py, cosmo_tester/test_suites/ha/__init__.py, cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py, cosmo_tester/test_suites/ha/ha_negative_test.py, cosmo_tester/test_suites/snapshots/__init__.py, cosmo_tester/test_suites/snapshots/multi_tenant_snapshot_test.py, cosmo_tester/test_suites/snapshots/single_tenant_snapshot_test.py
I've run all of the tests with the default attributes.yaml (testing on the default latest manager image for all tests on premium) and have had them all work, so there should be no negative impact on currently running tests.
The community tests have the following issues (which I don't think are down to problems with this PR):
1. The snapshot restore tests fail on 4.1 -> current, because of the presence of the cloudify stage files which cause the community manager to try to perform a restore of stage. This is probably best fixed by specifying community versions of the older managers too.
2. Bootstrap tests are currently failing because the bootstrap fails. I believe this is a problem with the current resources single tar.
=> CFY-7099 Support community images for testing

setup.py
=> CFY-7183 Remove the testnameextractor nose plugin

cosmo_tester/test_suites/snapshots/__init__.py
Due to resource constraints, the community snapshot tests need to be constrained temporarily.
=> Constrain community snapshot tests

cosmo_tester/resources/attributes.yaml
The CA cert is used for request verification, so this one needs to
be downloaded instead.
=> CFY-7190 Download the CA cert instead of the internal cert

cosmo_tester/resources/terraform/aws-osx-cli-test.tf
missed a comma in terraform file
=> Fix osx test

cosmo_tester/framework/cluster.py, cosmo_tester/framework/fixtures.py, cosmo_tester/test_suites/bootstrap_based_tests/inplace_upgrade_test.py, cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py, cosmo_tester/test_suites/bootstrap_based_tests/teardown_test.py, cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py, cosmo_tester/test_suites/ha/ha_negative_test.py, cosmo_tester/test_suites/snapshots/__init__.py
The staticmethods buy us very little, but add a nontrivial amount
of complexity. They do nothing interesting other than just pass
through arguments, but provide no additional abstraction.
Instead of having a `create` argument for the image_based (and one
is going to also be needed for bootstrap_based), we can simply
stop using the staticmethods, but instead always use the right
class directly.
The only non-obvious thing in create_bootstrap_based was setting
the image name, which of course should live in the class itself,
because without it, the class won't work. (it doesn't make sense
to have a class that can only possibly work when created through
the specific factory)
=> Replace CloudifyCluster.create_*_based with direct calls to subclasses

cosmo_tester/framework/git_helper.py
If the repo is already cloned, use what we have, don't attempt to clone again
=> git_helper: only clone if we didn't already clone before

cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py
Better differentiate between the different hello worlds, to avoid
clashes when all of them run on the default tenant in community
system tests.
=> CFY-7412 Fix multi network community system test

cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py
Otherwise, we might get an error that we tried to set-active to a node
that is offline (the node will then become online shortly after).
=> HA tests: before set-active, wait for cluster to stabilize

cosmo_tester/resources/attributes.yaml
The yum updated image requires a larger disk, and it's a waste to use it (and also, it will require further changes to the FW)
=> Revert Centos 7 image to the old one

cosmo_tester/resources/attributes.yaml
This OpenSSL version is necessary to install the new `nginx` version we're using now (`nginx-1.13.7-1.el7_4.ngx.x86_64`).
The error otherwise is:
```
Error: Package: 1:nginx-1.13.7-1.el7_4.ngx.x86_64 (/nginx-1.13.7-1.el7_4.ngx.x86_64)
Requires: libcrypto.so.10(OPENSSL_1.0.2)(64bit)
```
=> Update Centos image to one that include OpenSSL 1.0.2

cosmo_tester/framework/test_hosts.py
ruamel's loader doesn't handle `!!python/unicode` tags well, so we make
sure to keep the configuration strictly ASCII for test purposes
=> CFY-7684 Make sure the configuration yaml doesn't contain extra tags

cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py
...to allow the post-workflow methods of restore snapshot to run
=> multinetwork test: wait before upgrading agents

cosmo_tester/framework/examples/__init__.py, cosmo_tester/framework/examples/nodecellar.py, cosmo_tester/framework/test_hosts.py, setup.py
This is because now InfluxDB only binds on `localhost` (whereas it used
to bind on `0.0.0.0`), and we aren't able to access it via the manager's
public IP
=> CFY-7877 Access InfluxDB directly via SSH using curl

cosmo_tester/framework/examples/__init__.py, cosmo_tester/framework/examples/nodecellar.py, cosmo_tester/framework/test_hosts.py, cosmo_tester/resources/blueprints/openstack-start-vm/blueprint.yaml, cosmo_tester/resources/terraform/openstack-multi-network-test.tf.template, cosmo_tester/resources/terraform/openstack-vm.tf.template, cosmo_tester/test_suites/image_based_tests/auto_heal_test.py, cosmo_tester/test_suites/image_based_tests/hello_world_test.py
Preparation for making the metrics+policy engine not be in the manager by default.
=> CY-276 Default no metrics tests, except on heal

cosmo_tester/framework/test_hosts.py
In order to avoid Ruamel issues when passing those values to config.yaml
=> Convert network values from unicode to string

cosmo_tester/framework/test_hosts.py
If we don't wait, we might be in a state where the above (system-wide)
exec is still running and we're trying to start another one, which
might fail
=> Wait for plugin_install execution to finish after plugin upload

cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py, cosmo_tester/test_suites/ha/ha_negative_test.py
joining the cluster doesn't wait for the node to be passing all
health checks, so it was still possible to start a test method
while a replica node didn't fully finish joining, and was still
waiting for its manager-services healthcheck to go green
this change makes it so that we wait for the cluster to fully
stabilize before starting any test method
=> HA tests: before starting the test, wait to stabilize

cosmo_tester/framework/examples/__init__.py, cosmo_tester/framework/git_helper.py
This is unnecessary move because not all branches need to change the examples repos also
=> CY-166 : enable running system tests without creating a branch in the examples repos

cosmo_tester/framework/examples/__init__.py, cosmo_tester/framework/git_helper.py
Because we don't know if we deal with a branch or a tag, so
the simplest way is to relay on git checks.
=> CY-166 : fixing check if branch/tag exists

README.md, cosmo_tester/framework/examples/__init__.py, cosmo_tester/framework/test_hosts.py, cosmo_tester/framework/util.py
- Setting `CFY_LOGS_PATH_LOCAL` path as an env var will save logs of
test modules.
- Setting `SKIP_LOG_SAVE_ON_SUCCESS=True` will make sure not to save
logs when the tests are successful.
=> CY-586 Add log saving for tests

cosmo_tester/test_suites/snapshots/__init__.py, cosmo_tester/test_suites/snapshots/multi_tenant_snapshot_test.py, cosmo_tester/test_suites/snapshots/single_tenant_snapshot_test.py
Snapshot restore changes the credentials on manager post-execution.
If this happens to run before the test runs verify_services_status,
then the verify call will never succeed.
Instead, let's update the stored credentials before running those
requests, so that they run with the changed credentials already.
=> Snapshots: change credentials before running verify_services

cosmo_tester/framework/test_hosts.py
- Adds a log message before each step when attempting to save the manager's logs.
=> CY-586 Add more info messages for log save attempts

cosmo_tester/framework/fixtures.py, cosmo_tester/framework/test_hosts.py, cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py, cosmo_tester/test_suites/ha/ha_negative_test.py, cosmo_tester/test_suites/snapshots/__init__.py
Replaces old `log.tar.gz` file name format to `<Class Instance Name>__<Pytest Test Parameter (if reachable)>__<Instance Index in the TestHosts Instances List>__<Terraform Instance ID>`
=> CY-586 Add manager branch or image name as test tar file name prefix

cosmo_tester/test_suites/image_based_tests/cfy_manager_test.py
This way it can be used easily during snapshot restore
=> Move cryptography_utils to cloudify-common

cosmo_tester/framework/test_hosts.py
The concurrent workflows test fails fairly frequently with ~900 of its 1000 deployments prepared.
This suggests that it usually needs ~11% more time than it is allowed, so increasing the timeout attempts from 180 to 200 should allow that extra time.
=> Make concurrent workflows test more reliable

cosmo_tester/test_suites/summary/summary_test.py
This reverts commit 483c91fd61ff3ac0514cf6508b344c34b0b2a4ee.
=> Make summary tests work with null output from CLI

cosmo_tester/framework/util.py
due to github dropping support for password auth
=> github token: switching to github token

cosmo_tester/framework/util.py
Trying to acccess an env var that doesn't exist makes the test fail
after deploying VMs.
=> Fix get package url

cosmo_tester/test_suites/image_based_tests/ssl_test.py
The test is for external SSL, deploying hello world is unnecessary.
=> CY-2393 Stop deploying hello world on ssl test

cosmo_tester/framework/test_hosts.py, cosmo_tester/test_suites/agent/__init__.py, cosmo_tester/test_suites/agent/test_upgrade.py, cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py, cosmo_tester/test_suites/cluster/broker_management_test.py, cosmo_tester/test_suites/cluster/conftest.py, cosmo_tester/test_suites/cluster/db_management_test.py, cosmo_tester/test_suites/image_based_tests/inplace_upgrade_test.py, cosmo_tester/test_suites/manager_of_managers/constants.py, cosmo_tester/test_suites/snapshots/conftest.py
They're not necessary, so let's not upload them.
This also scraps sanity mode for manager tests.
=> CY-2450 Remove 'upload_necessary_files'

cosmo_tester/framework/test_hosts.py
Grepping like that only shows active units, but if ipsetter already finished,
it won't be in `systemctl`, but it will be in `systemctl -a`
=> TestHosts: use `systemctl -a`

cosmo_tester/conf_cli.py, cosmo_tester/test_suites/cluster/db_management_test.py
Some of the openstackrcs we have have v2.0 in the URL, which causes unhelpful errors.
This will replace them automatically with v3 if the config generation CLI tool is used.
=> Replace v2.0 with v3 in openstack auth URLs

cosmo_tester/config_schemas/package_urls.yaml
Community tests will fail with premium nulled otherwise.
=> Don't require package urls to be set

cosmo_tester/test_suites/service_composition/component_test.py
Because of the automatic deletion of deployment since the new examples were introduced,
the expected deployment count was incorrect.
=> CY-3259 Check correct dep count in component test

cosmo_tester/framework/test_hosts.py
hashlib takes bytes. We need to encode the paths.
This is enough to make the cluster test run on py3
=> Encode paths to hash

cosmo_tester/framework/test_hosts.py
Although Fabric specifies in the documentation that the `key_filename` value should be a string, it sometimes throws an error when it's not given as part of a list. We haven't figured out yet what "sometimes" means, but for now, we'll put the key file path in a list.
=> Changing key-path to list

cosmo_tester/test_suites/cluster/conftest.py, cosmo_tester/test_suites/cluster/full_cluster_test.py
We need to add a three-nodes-cluster pytest fixture so it can be used in our system tests.
=> CY-3586 Adding three-nodes-cluster fixture

cosmo_tester/config_schemas/cfy_cluster_manager.yaml, cosmo_tester/test_suites/cluster/cfy_cluster_manager.py, cosmo_tester/test_suites/cluster/cfy_cluster_manager_resources/nine_nodes_config.yaml, cosmo_tester/test_suites/cluster/cfy_cluster_manager_resources/three_nodes_config.yaml
This PR:
1. Removes the db_monitoring from the config files. 
2. Changes minor things in the tests themselves.
=> Changes to cfy-cluster-manager tests

cosmo_tester/framework/test_hosts.py, cosmo_tester/test_suites/snapshots/inplace_upgrade_test.py
The snapshot inplace upgrade test fails while trying to uninstall the example deployment. This happens, as far as I understand, because the uninstall task is sent to the rabbitmq before it is initialized.
Waiting for the rabbitmq to be alive, should fix it -> well, it didn't.
Giving the manager more time to initialize (by increasing the sleep time) worked.
=> RD-838 Fix snapshots inplace upgrade system test

cosmo_tester/test_suites/summary/summary_test.py
We've added an additional workflow, and so it now appears in the
summary tests
=> RD-1063 add upload_blueprint to summary tests

cosmo_tester/config_schemas/cfy_cluster_manager.yaml, cosmo_tester/test_suites/cluster/cfy_cluster_manager_test.py
[This change to cloudify-cluster-manager](https://github.com/cloudify-cosmo/cloudify-cluster-manager/pull/69) copies the config.yaml file at the end of each service's installation to the service's config.yaml file. This caused `cosmo_tester/test_suites/cluster/cfy_cluster_manager_test.py::test_three_nodes_using_provided_config_files` to fail since it was asserting that the services' config files are equal to the ones that were provided (which was not true anymore). 
This PR fixes it by changing the assertion to assert that the provided config files are equal to the services' config files at /tmp/cloudify_cluster_manager/config_files which are used for the installation, and are not being overriden.
=> RD-1090 Update cfy-cluster-manager config files test

requirements.txt
This reverts to the previous reqs.txt, which are compatible
with py2.
The rewritten reqs.txt would've been only compatible with py3.
But we still run tests on py2 on jenkins
The change between this commit and master is that I've of course kept
the 5.2.0-build.zip for cloudify-common
=> Revert to older requirements.txt

cosmo_tester/framework/test_hosts.py
We don't call the cfy_manager wait-for-starter because it checks supervisord
rather than systemd (and sometimes it's just not installed at all).
=> Wait for image starter

cosmo_tester/config_schemas/platform_aws.yaml, cosmo_tester/framework/test_hosts.py, cosmo_tester/resources/infrastructure_blueprints/aws/infrastructure-multi-net.yaml, cosmo_tester/resources/infrastructure_blueprints/aws/infrastructure.yaml, cosmo_tester/resources/infrastructure_blueprints/aws/vm-multi-net.yaml, cosmo_tester/resources/infrastructure_blueprints/aws/vm.yaml, cosmo_tester/test_suites/cluster/conftest.py
They don't pass, but they can at least run. The failures now are either from the agent itself or from the test code, with reasonably suspicion being cast one way or the other when I run more agent tests.
=> Rd 717 Make windows agent tests able to run

cosmo_tester/config_schemas/platform_aws.yaml
The old images were hvm:instance-store, which causes an error when building. These are hvm:ebs-ssd, which deploy successfully.
=> RD-717 Use correct type of ubuntu images on AWS

cosmo_tester/config_schemas/platform_aws.yaml, cosmo_tester/config_schemas/platform_openstack.yaml, cosmo_tester/config_schemas/test_os_usernames.yaml, cosmo_tester/test_suites/agent/test_reboot.py
We can't build RHEL 6 agents any more so let's not test them.
=> Remove RHEL 6 from testing

cosmo_tester/framework/constants.py, cosmo_tester/test_suites/cluster/cfy_cluster_manager_shared.py, cosmo_tester/test_suites/cluster/compact_cfy_cluster_manager_upgrade_test.py, cosmo_tester/test_suites/cluster/full_cfy_cluster_manager_upgrade_test.py, cosmo_tester/test_suites/general/cfy_manager_test.py
According to Ofer, we don't support upgrading from v5.1.0 using `cfy_manager upgrade`, so we should also remove it from the tests.
=> Remove 5.1.0 from upgrade base versions

cosmo_tester/test_suites/snapshots/inplace_restore_test.py
After restoring the snapshot, we wait for the manager to come back
up, because the snapshot-restore includes a reboot.
Only THEN we wait for agents. Why would we wait for agents before
the manager was up?
The order of operations is:
1. snap-restore
2. reboot
3. wait for manager to come back up
4. wait for agents to reconnect
Before this change, 3 and 4 were swapped
=> RD-858 test_inplace_restore: wait_for_manager after snap-restore

cosmo_tester/test_suites/cli/__init__.py
this is necessary since `var/log/cloudify/rabbitmq/log` is now unreadable outside the `cfyuser` group
=> RD-2462 Run verify logs purged with sudo

README.md, cosmo_tester/config_schemas/manager_image_names.yaml, cosmo_tester/config_schemas/manager_image_names_centos.yaml, cosmo_tester/config_schemas/manager_image_names_rhel.yaml, cosmo_tester/framework/test_hosts.py, cosmo_tester/test_suites/cluster/conftest.py
Given that the starter service just does a configure anyway, this is
effectively doing the same thing, but reducing the code paths.
Additionally, this means that we don't need to replace certs any more
because we are bootstrapping the node with the right IPs on the certs.
=> RD-2468 Always bootstrap test nodes

requirements.txt
Because with an updated version of openssl a bug in paramiko becomes
breaking. This was fixed in the latest update.
=> RD-2527 Update paramiko version

cosmo_tester/test_suites/cluster/cfy_cluster_manager_test.py
This PR modifies the `test_three_nodes_cluster_using_provided_certificates` test logic to cope with the changes introduced here https://github.com/cloudify-cosmo/cloudify-cluster-manager/pull/89. 
Basically, adding the CA key in the use case of provided certificates.
=> RD-2583 Add CA key to cfy_cluster_manager config

cosmo_tester/test_suites/cluster/full_cluster_test.py
They use 9 VMs now, so the tests needed updating.
=> Use correct VM counts in full cluster tests

cosmo_tester/framework/test_hosts.py
Now we delete the known hosts entry once so that trust-on-first-use works again.
We also allow passing commands to the script- e.g. {path}/ssh_0 sudo supervisorctl status
(which allows checking the same thing on all linux test vms more easily)
=> Improve ssh scripts

cosmo_tester/framework/test_hosts.py
If it really failed then a message will be given when the user tries to
use the ssh script.
In the Jenkins environment it can fail (probably due to the absence of
the known_hosts file).
=> Don't abort test if forgetting ssh key fails

cosmo_tester/test_suites/agent/test_upgrade.py
Avoid transferring the stdout itself, because that's gonna be unknown
encoding; instead, just work in terms of returncodes
=> RD-2675 test-agents-upgrade: replace checking stdout with grep

cosmo_tester/test_suites/agent/test_upgrade.py
Avoid transferring the stdout itself, because that's gonna be unknown
encoding; instead, just work in terms of returncodes
=> RD-2675 test-agents-upgrade: replace checking stdout with grep (#1263)

cosmo_tester/test_suites/bootstrap_based_tests/teardown_test.py
... it's not /opt/cloudify-agent-5.2.0 but /opt/cloudify-agent-5.2.4
=> RD-2708 Update cloudify-agent directory/folder name

cosmo_tester/test_suites/cluster/conftest.py
When setting up cluster nodes, we sometimes have nodes that aren't cloudify nodes,
e.g. a load balancer. These nodes do not have an install_config.
=> Do not set install_config on non-cloudify nodes

cosmo_tester/test_suites/bootstrap/teardown_test.py
The agent itself gets removed, leaving the dir empty, but then the dir isn't cleaned up.
As there could technically be multiple agents this is maybe not a bug on the agent side.
However, as we know there won't be multiple agents, we should be able to remove it in the
test, and fail if we can't.
=> Remove agents dir on teardown test

cosmo_tester/conftest.py, cosmo_tester/test_suites/bootstrap/teardown_test.py
Otherwise the previous test can leave some resources behind which means we
can't check that everything we expect to be created/deleted/remaining is.
=> RD-2723 Isolate teardown test (don't reuse VM)

cosmo_tester/framework/test_hosts.py, cosmo_tester/resources/infrastructure_blueprints/aws/infrastructure-ipv6.yaml, cosmo_tester/resources/infrastructure_blueprints/aws/vm-ipv6.yaml, cosmo_tester/test_suites/cluster/compact_cluster_test.py, cosmo_tester/test_suites/cluster/conftest.py
* Add {infrastructure,vm}-ipv6-net blueprints, these are use to test
IPv6-enabled cluster
* Add test_three_nodes_cluster_ipv6_status and ipv6 fixtures
* Use ipv6_address as a private_ip_address in ipv6_net test.
The `private_ip_address` is actually used as both `private_ip` and
`public_ip` in `/etc/cloudify/config.yaml`.
* Disable IPv4 in case of IPv6 test(s)
* Add a comment about IPv4 in the vm-ipv6-net blueprint
* Make a blueprint suffix generation more readable and easier to extend
* Add a comment on disabling IPv4 in a cluster
* Rename blueprints: `ipv6` without `-net` suffix
* Verify agent too
=> RD-2425 IPv6 cluster test

cosmo_tester/framework/util.py
Sometimes AWS takes its time creating resources, so let's wait longer.
=> Increase execution wait time

cosmo_tester/test_suites/bootstrap/teardown_test.py
It's expected to be used in general, so we should make sure it doesn't leak resources.
=> Include sanity for teardown test

aws_cleanup
The VPC MUST be tagged, but we will now delete all child resources
of any correctly tagged VPC when we try to.
The only resource we can now leak is EIPs because they don't belong
to a VPC, so if they're not tagged... sadness is a thing.
Estimate age will also return hours above 24 now.
=> Make cleanup script cope with untagged resources

cosmo_tester/resources/blueprints/compute/example_2_files.yaml
The same inputs need to be present when not updating inputs.
=> Update BP for updating example

cosmo_tester/resources/blueprints/compute/example_2_files.yaml
The old blueprint should actually have worked, so we'll leave this as it was.
=> Roll back BP update for dep update

cosmo_tester/test_suites/cluster/conftest.py
This became necessary since we've changed the permissions of cloudify folders in 6.3.0
=> Remove directories created by the installer

cosmo_tester/conftest.py, cosmo_tester/test_suites/cluster/conftest.py
This makes a single test much quicker to run locally.
=> Don't run session logic (backup/restore) on 1 test

cosmo_tester/test_suites/cluster/conftest.py
This happens right at the start of the fixture, and appears to have caused
a pile of failures in yesterday's tests.
=> Wait for SSH before rebooting if required

cosmo_tester/framework/test_hosts.py
Otherwise we can have test CA or cfy profiles contaminating later tests.
=> Clean up homedirs between tests

cosmo_tester/framework/test_hosts.py
Otherwise we can end up with the wrong CA and a verify fail.
=> Clean local rest CA between tests

cosmo_tester/test_suites/cluster/broker_management_test.py
It wasn't using the correct config. It will now.
=> Fix kill_node in broker management tests

cosmo_tester/framework/test_hosts.py, cosmo_tester/test_suites/cluster/broker_management_test.py, cosmo_tester/test_suites/cluster/cfy_cluster_manager_shared.py
We also check there is at least one main service before trying to run the stop,
because currently the installer doesn't clear up others (and those others should
not be there anyway, as they're components of the actual services we provide).
=> Don't leak installed config list between tests

cosmo_tester/conftest.py
There's no point, we do the same restore procedure we do on cluster managers.
=> Don't tear down between tests on session managers

cosmo_tester/config_schemas/platform_aws.yaml, cosmo_tester/framework/test_hosts.py
We know 2.8.0 works, we know 2.14.0 deletes important images.
Let's just pin to 2.8 for now as we're near release.
=> Don't allow dangerous versions of AWS plugin

cosmo_tester/test_suites/cluster/full_failover_test.py
30 seconds was a little close to the line and caused some failures.
=> Wait longer for broker to become healthy

cosmo_tester/resources/blueprints/proxy/proxy_blueprint.yaml, cosmo_tester/resources/blueprints/proxy/scripts/download_via_proxy.py, cosmo_tester/test_suites/bootstrap/proxy_test.py
Set up http proxy in the manager, and check that we do use it.
Importantly, I have checked that it also uses the proxy for stage,
although we don't have a way to automatically assert it here.
=> RD-4188 Add a test that uses http proxy

cosmo_tester/framework/test_hosts.py, cosmo_tester/test_suites/general/cfy_manager_test.py
We can't do this on cluster upgrade tests because cluster manager gets in the way.
=> Support overriding c-m-i on upgrade tests

cosmo_tester/test_suites/cluster/external_component_cluster_test.py, cosmo_tester/test_suites/cluster/full_cluster_test.py, cosmo_tester/test_suites/snapshots/__init__.py
It's no longer needed as the passwords are randomised on different servers.
=> Remove static password change from systests

cosmo_tester/test_suites/agent/test_upgrade.py, cosmo_tester/test_suites/cluster/cluster_to_aio_agents_migration_test.py, cosmo_tester/test_suites/multi_net/multi_network_test.py
It is picked up from the old manager object, so was removed as a parameter.
=> Don't call snapshots with password

cosmo_tester/test_suites/cluster/cluster_status_shared.py
We've seen the occasional race here, so let's allow a minute for recovery.
=> Allow 1 minute for all cluster status checks

cosmo_tester/framework/test_hosts.py
This may help us troubleshoot an intermittent problem we occasionally see
during system tests.
=> Give more detail when bootstrap fails

cosmo_tester/test_suites/cluster/full_failover_test.py
Log access is less generally allowed now.
=> Check logs with sudo on failover test

cosmo_tester/framework/deployment_update.py
There's an interesting side bug that could've done this (but instead blew up another way),
so let's make sure we catch it if it ever does happen.
=> Make sure new file isn't recreated on update

cosmo_tester/test_suites/snapshots/__init__.py
We're overrunning the retries on RH8 tests.
=> Increase retries for snapshots

cosmo_tester/test_suites/multi_net/multi_network_test.py
Centos agents currently won't work without python 3 installed.
=> Use RHEL8 for agent VMs on multi-net tests

cosmo_tester/test_suites/agent/test_reboot.py, cosmo_tester/test_suites/agent/test_upgrade.py, cosmo_tester/test_suites/multi_net/multi_network_test.py, cosmo_tester/test_suites/snapshots/conftest.py, cosmo_tester/test_suites/snapshots/inplace_restore_test.py
Switched to RH8 in most cases, just removed for actual agent tests.
Can be reintroduced once we handle missing py3 for agent install.
=> Remove remaining centos 7 agents

cosmo_tester/test_suites/agent/test_reboot.py
Agents don't support python 3.5 any more because they use fstrings.
Therefore, let's not test this- and it's in extended support so
we might want to reconsider which Ubuntu versions we test.
=> Don't test Xenial agent

cosmo_tester/config_schemas/platform_aws.yaml
The old one appears to have been deleted, though that's not currently reflected in: https://access.redhat.com/solutions/15356#eu_west_1_rhel7
=> Update RHEL 7 AMI

cosmo_tester/test_suites/cluster/conftest.py
It's not in the installer RPM any more.
=> Install haproxy from OS repos

cosmo_tester/test_suites/agent/__init__.py
"manylinux" isn't a system, but "linux" is.
=> RD-6658 agent systests: the system name is "linux"

cosmo_tester/test_suites/agent/__init__.py
The agent list contains the old "UPGRADED"/"STOPPED" agent, and a new "STARTED" agent. Only assert on the new one.
=> RND-293 agent upgrade test: only assert on the STARTED agent

cosmo_tester/test_suites/agent/__init__.py
The agent list contains the old "UPGRADED"/"STOPPED" agent, and a new "STARTED" agent. Only assert on the new one.
=> RND-293 agent upgrade test: only assert on the STARTED agent (#1535)

cosmo_tester/test_suites/cluster/cfy_cluster_manager_resources/config_files_templates/manager_config.yaml, cosmo_tester/test_suites/cluster/conftest.py, cosmo_tester/test_suites/snapshots/inplace_restore_test.py
Currently, separate external certs are only supported when public_ip is a domain name, not an ip, and these tests always provide ips.
This is because both internal and external listen on 443, and SNI only works for domain names, not ips.
=> Do not pass external_cert/key/ca

cosmo_tester/test_suites/cluster/cfy_cluster_manager_shared.py
Since we can no longer provide public IPs together with external certificates, let's use pseudo-FQDNs in the cluster-manager config for the cluster upgrade tests. We don't need to know the actual FQDNs since the tests never use them.
=> Cluster manager tests: public IPs -> FQDNs

cosmo_tester/framework/test_hosts.py, cosmo_tester/framework/util.py
Close the session after fetching the cert, so that next request re-loads the cert, instead of using the old cert and throwing an error.
Alternatively, we could just send a dummy request, that would fail with a SSLError - that also causes a reload, so the next request would pass. But that would be silly :)
Also speedup `delete_deployment`. Heh.
=> RND-901 Download new rest cert: re-establish the http session

cosmo_tester/framework/test_hosts.py
This solves the issue of teardown process not being able to restore rsync-ed backups in environment with less lax umask settings.
=> RND-948 Make /cfy_backup/ readable to all
