cloudify-cosmo/cloudify-system-tests

- cosmo_tester/test_suites/test_blueprints/nodecellar_test.py
I want to use the NodecellarAppTest class for the docker plugin system tests, so i needed to make some of these properties so I can override them.
> made properties for repo_url and blueprint_directory

- suites/suites/suites.yaml
Seems like I didn't commit the right image id and micro instance type
> TFY-14-Correct-Trusty-Image-ID-AWS

- suites/suites/suites.yaml
I am trying to open the port 8086 in aws ec2 manager during system tests.
> TFY-15 Added manager override

- cosmo_tester/resources/blueprints/openstack-start-vm/blueprint.yaml
- cosmo_tester/test_suites/test_blueprints/nodecellar_test.py
- cosmo_tester/test_suites/test_simple_manager_blueprint/__init__.py
- cosmo_tester/test_suites/test_simple_manager_blueprint/nodecellar_singlehost_test.py
- suites/suites/suites.yaml
and refactored the basic nodecellar test
> CFY-2613 added test for simple manager

- cosmo_tester/framework/assertions.py
- cosmo_tester/framework/test_cases.py
- cosmo_tester/test_suites/test_blueprints/hello_world_bash_test.py
- cosmo_tester/test_suites/test_blueprints/nodecellar_test.py
CFY-2640-Add-monitoring-test-to-system-test-for-Hello-World-Example
> CFY-2640-Add-monitoring-test-to-system-test-for-Hello-World-Example

- cosmo_tester/resources/blueprints/openstack-cinder/file-system-blueprint.yaml
- cosmo_tester/resources/blueprints/openstack-cinder/scripts/substitute_chown.sh
- cosmo_tester/resources/blueprints/openstack-cinder/scripts/write-to-volume.sh
One test modified to additionally test volume attachment reentrancy
> Cfy 2422 idempotent volume attachment

- cosmo_tester/test_suites/test_manager_recovery/manager_recovery_base.py
Killing container before 'recovery' seems to cause the following 'stop' container command to block indefinitely. Due to moving away from a docker based manager, it is decided that we will simply remove the kill for now as investigating it will be a waste of time
> Fix recovery test

- cosmo_tester/framework/cfy_helper.py
- cosmo_tester/framework/git_helper.py
- cosmo_tester/resources/scripts/snapshots_migration_scripts/bootstrap_manager_3_2_1.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/clear_manager_3_2_1.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/create_and_download_snapshot_3_2_1.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/helloworld_inputs.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/install_helloworld_3_2_1.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/manager_3_2_1_inputs.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/manager_3_3_inputs.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/prepare_cli_3_2_1.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/teardown_manager_3_2_1.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/update_user_and_credectials_3_2_1.template
- cosmo_tester/resources/scripts/snapshots_migration_scripts/update_user_and_credentials_3_2_1.py
- cosmo_tester/test_suites/test_snapshots_from_321_to_33/__init__.py
- cosmo_tester/test_suites/test_snapshots_from_321_to_33/hello_world_old_new_manager_test.py
- suites/suites/suites.yaml
> Added test that tests snapshot migration from manager 3.2.1 to manager

- cosmo_tester/resources/blueprints/active-directory/active-directory-blueprint.yaml
- cosmo_tester/resources/blueprints/active-directory/scripts/wait_for_active_directory_port.sh
- cosmo_tester/test_suites/test_security/ad_auth_test.py
- cosmo_tester/test_suites/test_security/auth_test_base.py
- cosmo_tester/test_suites/test_security/authentication_test.py
- cosmo_tester/test_suites/test_security/authorization_tests.py
- cosmo_tester/test_suites/test_security/no_userstore_tests.py
- cosmo_tester/test_suites/test_security/security_test_base.py
- suites/suites/suites.yaml
Conflicts:
suites/suites/suites.yaml
Conflicts:
suites/suites/suites.yaml
> CFY-3717 active directory test

- cosmo_tester/test_suites/test_blueprints/nodecellar_test.py
The 'uninstall' cleanup now handles the case of already uninstalled
deployment correctly.
> Make the cleanup idempotent in nodecellar test

- cosmo_tester/test_suites/image_based_tests/agent_installation_test.py
> Agent userdata tests fixups for 4.1.1.1-build

- cosmo_tester/test_suites/image_based_tests/agent_installation_test.py
> CFY-7124 Userdata test fixups

- cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py
- cosmo_tester/test_suites/ha/ha_helper.py
- stop nginx on leader
- check that a new leader is elected
- stop mgmtworker on that new leader, and restart nginx on the former
- check that the original leader was elected
> CFY-7146 HA system tests: fix test_failover

- cosmo_tester/framework/cluster.py
- cosmo_tester/framework/util.py
- cosmo_tester/resources/attributes.yaml
- cosmo_tester/test_suites/bootstrap_based_tests/cli_test.py
- cosmo_tester/test_suites/ha/__init__.py
- cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py
- cosmo_tester/test_suites/ha/ha_negative_test.py
- cosmo_tester/test_suites/snapshots/__init__.py
- cosmo_tester/test_suites/snapshots/multi_tenant_snapshot_test.py
- cosmo_tester/test_suites/snapshots/single_tenant_snapshot_test.py
Reverts cloudify-cosmo/cloudify-system-tests#562
> Revert "CFY-7099 Support community images for testing"

- cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py
This should verify that the manual mechanism of adding a network works
as expected
> CFY-7318 Update multi network test to add a network post-bootstrap

- cosmo_tester/framework/util.py
- cosmo_tester/test_suites/snapshots/__init__.py
- cosmo_tester/test_suites/snapshots/multi_tenant_snapshot_test.py
- cosmo_tester/test_suites/snapshots/single_tenant_snapshot_test.py
- test-requirements.txt
Will cause master -> master snapshot tests to fail unless https://github.com/cloudify-cosmo/cloudify-manager/pull/987 is merged.
> CFY-7305 Test restored users are fixed

- cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py
Test scenario:
- setup a proxy that forwards all connections on ports 5671 and 53333
to the manager
- set the manager's default network to the proxy ip
- block all connections to the manager except from the proxy
- check that agents can still work and connect to the manager (through
the proxy)
> CFY-7319 Proxy multinetwork test

- cosmo_tester/test_suites/image_based_tests/hello_world_test.py
See comment in the commit for the reasoning behind the change
> CYBL-285 Fix backwards compatibility hello world test

- cosmo_tester/test_suites/scale/concurrent_workflows_test.py
> fix params type

- cosmo_tester/framework/test_hosts.py
- Added retries to log saving
- Added `except Exception` catch to ignore failed save log attempts
> CY-586 Add retry logic and exception catch for save logs

- cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py
- cosmo_tester/test_suites/bootstrap_based_tests/sanity_scenario_test.py
- cosmo_tester/test_suites/ha/__init__.py
- cosmo_tester/test_suites/ha/ha_cluster_scenarios_test.py
- cosmo_tester/test_suites/ha/ha_helper.py
- cosmo_tester/test_suites/ha/ha_negative_test.py
Also refactored `ha_helper.py` (best read commit-by-commit)
> Add a multinetworks+cluster test

- cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py
Use new multi-network configuration layout
> Fix multi-network tests

- cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py
The new clustering is different enough to the old clustering that we'll need to
redo this test.
> Remove multi-net cluster until new cluster is done

- cosmo_tester/resources/terraform/openstack-linux-cli-test.tf
- cosmo_tester/resources/terraform/openstack-multi-network-test.tf.template
- cosmo_tester/resources/terraform/openstack-vm.tf.template
- cosmo_tester/resources/terraform/openstack-windows-cli-test.tf
define allocation pools for subnets
> Fixing rackspace timeout with terraform

- cosmo_tester/resources/agent/userdata-agent-blueprint/userdata-agent-blueprint.yaml
Unfortunate but this validation is useless
> Userdata blueprint: disable openstack validation

- setup.py
- remove node due that it's not used
> requirements: updating outdated packages

- cosmo_tester/test_suites/snapshots/__init__.py
- cosmo_tester/test_suites/snapshots/multi_tenant_snapshot_test.py
to test the new 'snapshot-status' endpoint
> CY-1538 Add a status check to the snapshot test

- cosmo_tester/test_suites/bootstrap_based_tests/teardown_test.py
The system might create additional log dirs not related to cloudify
while we're running the test, so don't pay attention to those
> test_teardown: skip OS log dirs

- cosmo_tester/framework/git_helper.py
- cosmo_tester/framework/util.py
> Remove deprecated uses of path()

- cosmo_tester/framework/test_hosts.py
It already has _OldStatus via Cloudify4_6Manager
> Fix Cloudify4_6Manager_ClusterJoined bases

- cosmo_tester/test_suites/ui_tests/composer_test.py
- cosmo_tester/test_suites/ui_tests/stage_test.py
Which is set in the jenkins job
> ui tests - switch to get test host ip from env var

- cosmo_tester/framework/test_hosts.py
- cosmo_tester/resources/attributes.yaml
- cosmo_tester/test_suites/cluster/conftest.py
* The format of db and rabbit nodes in the config.yaml was changed.
* Update those changes in the cluster system tests.
> CY-1910 Fix cluster system tests

- cosmo_tester/test_suites/cluster/db_management_test.py
* The node_id argument was added to db-node-add and db-node-remove commands
* Update the tests to use it
* Change the names of cfy_manager commands when needed
> CY-1902 Update system tests of db cluster operations

- cosmo_tester/framework/test_hosts.py
- cosmo_tester/resources/attributes.yaml
- cosmo_tester/test_suites/snapshots/__init__.py
> Cy 1537 add snapshot tests 5.0.5

- cosmo_tester/test_suites/cluster/broker_management_test.py
- cosmo_tester/test_suites/cluster/conftest.py
- Add missing broker info assert
- Update to date how adding a broker is done
> CY-2243: fixing broker list test

- cosmo_tester/framework/util.py
instead of a function from cli, which doesn't exist anymore
> get_cli_version: use pkg_resources

- cosmo_tester/test_suites/manager_of_managers/regional_cluster.py
Otherwise, pytest can fail to collect tests in some situations (but not others, great).
> Remove AbstractExample import from MoM

- cosmo_tester/test_suites/manager_of_managers/mom_test.py
- cosmo_tester/test_suites/manager_of_managers/regional_cluster.py
pytest --collectonly now works on that directory.
> Remove defunct components from MoM tests

- cosmo_tester/framework/test_hosts.py
- cosmo_tester/framework/util.py
- cosmo_tester/test_suites/cluster/__init__.py
- cosmo_tester/test_suites/cluster/conftest.py
- cosmo_tester/test_suites/cluster/db_management_test.py
- cosmo_tester/test_suites/cluster/full_cluster_test.py
- cosmo_tester/test_suites/snapshots/__init__.py
This includes making the install+uninstall run in parallel, as well as several problems I then encountered while trying to find out how much the performance differed.
> Test fixups

- cosmo_tester/test_suites/bootstrap_based_tests/teardown_test.py
This will still fail as there are several issues we should care about,
for which jiras will be opened.
> Update checks on teardown

- cosmo_tester/test_suites/cluster/db_management_test.py
- cosmo_tester/test_suites/cluster/full_cluster_test.py
The `full_cluster` fixture was changed to `full_cluster_ips`.
> Replacing deleted full-cluster fixture

- cosmo_tester/framework/logger.py
I prefer logs in my console, not in the config files I redirected to
> Move logging to stderr

- cosmo_tester/framework/exceptions.py
- cosmo_tester/framework/test_hosts.py
This is all that's needed to make this run py3.
The basic test, at least.
> Replace StandardError with Exception

- cosmo_tester/test_suites/cluster/conftest.py
Hostname collisions will cause config.yaml entries keyed on hostnames to
collide and thus result in things like having only one defined rabbit and
make the bootstrap fail.
> CY-3248 Avoid hostname collisions in cluster tests

- cosmo_tester/test_suites/ui_tests/composer_test.py
- cosmo_tester/test_suites/ui_tests/stage_test.py
Note: this PR should be merged only once stage and composer next branches are merged to master.
> CY-2876 Updated stage and composer test suites to handle coverage

- cosmo_tester/resources/blueprints/cli/test-ec2-fileserver-vm-blueprint.yaml
- cosmo_tester/resources/blueprints/cli/test-ec2-linux-vm-blueprint.yaml
- cosmo_tester/resources/blueprints/cli/test-ec2-windows-vm-blueprint.yaml
- cosmo_tester/resources/blueprints/cli/test-os-fileserver-vm-blueprint.yaml
- cosmo_tester/resources/blueprints/cli/test-os-linux-vm-blueprint.yaml
- setup.py
This reverts commit e524c91a229abd4296c278f45536ebe4e6c5a242.
> Revert "Bump version"

- cosmo_tester/config_schemas/manager_image_names_centos.yaml
- cosmo_tester/config_schemas/manager_image_names_rhel.yaml
- cosmo_tester/framework/util.py
- cosmo_tester/test_suites/cluster/conftest.py
- cosmo_tester/test_suites/cluster/full_cluster_test.py
- cosmo_tester/test_suites/image_based_tests/cfy_manager_test.py
This PR currently takes care only of the 3 nodes case. Once it is approved, I'll continue for the 9 nodes.
> RD-874 Add cluster upgrade system tests

- cosmo_tester/test_suites/image_based_tests/deployment_update_test.py
after async blueprint uploads, we need to add waits after uploading them
> test_simple_update: wait for blueprint upload

- cosmo_tester/framework/test_hosts.py
- cosmo_tester/test_suites/bootstrap_based_tests/multi_network_test.py
- cosmo_tester/test_suites/cluster/__init__.py
- cosmo_tester/test_suites/cluster/broker_management_test.py
- cosmo_tester/test_suites/cluster/full_cluster_test.py
- cosmo_tester/test_suites/image_based_tests/test_tenant_creation_rabbitmq_down.py
- cosmo_tester/test_suites/snapshots/__init__.py
> Use supervisorctl for manager services

- cosmo_tester/test_suites/cluster/full_cluster_test.py
These are handled by the cfy cluster manager tests.
As we've now retired the alternative way of upgrading, these are
just taking time and not providing value.
> Remove upgrade tests from full_cluster_test

- cosmo_tester/test_suites/multi_net/multi_network_test.py
HAProxy should use systemctl instead of supervisorctl
> Change supervisorctl to systemctl in agents test

- cosmo_tester/framework/test_hosts.py
Previously this was only done for 'auto' proto rest clients,
but that results in failures using the rest client on the
remove-db test as the cert isn't present.
> RD-2677 Download cert when making rest client

- cosmo_tester/test_suites/snapshots/inplace_restore_test.py
Replacing the certs will either break rabbit (if the rabbit cert is replaced)
or the agents (if the manager is installed with different rabbit certs),
so instead we do the inplace install with the same certs.
> RD-2683 Reuse certs on inplace restore

- cosmo_tester/test_suites/cluster/compact_cluster_test.py
Same as we did for cert replacement tests. Test now passes
> RD-2726 Add cert copy to infra after new bootstrap

- cosmo_tester/test_suites/cluster/broker_management_test.py
This is necessary since we've started to use sessions which share hosts. the changes one test makes to the `/etc/hosts` file may affect other tests in unpredictable ways
> RD-2725 Clean changes in the hosts file after each test

- aws_cleanup
This backports yuval's cleanup script update.
> Add region to clean-up script

- cosmo_tester/config_schemas/cfy_cluster_manager.yaml
This is the 6.2.0 version of https://github.com/cloudify-cosmo/cloudify-system-tests/pull/1346
> RD-3128 Update cluster manager

- cosmo_tester/framework/test_hosts.py
We've seen something that looks like it had to be a failure trying to mv.
This should make errors in this clear.
> Log mv output on bootstrap

- cosmo_tester/test_suites/general/folder_permissions_test.py
The old one was a bit more in depth than required, and was unnecessarily failing.
> Check desired folder permissions

- cosmo_tester/test_suites/cluster/db_management_test.py
Removing them doesn't work quite as well, of course.
> Add DBs on add DB node test

- cosmo_tester/framework/test_hosts.py
Otherwise we end up with contamination and fun errors.
> RD-3991 Revert install config between tests

- cosmo_tester/framework/test_hosts.py
There's another one that can get raised- presumably since the SSH change.
> Add another timeouterror

- cosmo_tester/test_suites/cluster/broker_management_test.py
> Don't use --force in remove any more

- cosmo_tester/config_schemas/test_manager.yaml
- cosmo_tester/framework/test_hosts.py
- cosmo_tester/framework/util.py
- cosmo_tester/test_suites/cluster/conftest.py
Otherwise we put publically accessible VMs up with default passwords in most cases.
> Randomise passwords on test VMs

- cosmo_tester/config_schemas/platform_aws.yaml
> Use newly created windows image

- cosmo_tester/test_suites/cluster/full_failover_test.py
> Use SS not netstat

- cosmo_tester/config_schemas/platform_aws.yaml
- cosmo_tester/framework/test_hosts.py
This is to try to avoid issues with the plugin deleting images.
> Use different account for images

- cosmo_tester/test_suites/agent/test_retry.py
Similar to what https://github.com/cloudify-cosmo/cloudify-system-tests/pull/1484 does on `master`
> RD-5243 Test for broken agent/manager connection

- requirements.txt
Wagon version requirement changed in c-c, so let's update all the deps.
> RD-6509 Update dependencies

- cosmo_tester/config_schemas/platform_aws.yaml
Latest image as referenced by https://www.centos.org/download/aws-images/
> RD-6555 Update Centos 7 AMI

- aws_cleanup
Adding the feauture to delete leftover resources from past tests that are unkown regarding its lack of name and owner
> Adding deleting unknown resources feature.

- cosmo_tester/test_suites/summary/summary_error_test.py
https://github.com/cloudify-cosmo/cloudify-manager/pull/4162/files#diff-58eab464a482b26d383e199201afa68ca0e8eaa6b611dc5aeeaa186fc13d6baeR59
> Fix summary error message check after RND-390

- cosmo_tester/test_suites/auth/test_saml.py
- cosmo_tester/test_suites/cluster/broker_management_test.py
- cosmo_tester/test_suites/snapshots/multi_tenant_snapshot_test.py
Fixes at least one test: `cosmo_tester/test_suites/auth/test_saml.py::test_saml_auth`
> RND-959 Preserve ownership/permissions when copying

- cosmo_tester/framework/test_hosts.py
- cosmo_tester/resources/blueprints/compute/example.yaml
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-system-tests/pull/1582
> Pre 7.0.3 release fixes (part 2)
